// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Connection URL for the Prisma CLI (migrate, studio). At app runtime the URL
  // is passed to PrismaClient through a driver adapter — see lib/db.ts.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
